version: "2.1"

services:
  archiver:
    image: sensebox/osem-archiver:latest
    environment:
      SLACK_HOOK_URL: <Slack webhook url to notify run errors>
      DAV_USER: <Username for the webdav instance>
      DAV_PASS: <Password for the webdav instance>
      DAV_URL: <The URL for your webdav instance>
      ARCHIVE_FOLDER: <the base folder where you want to store the archive>
      MONGO_USER: <Username of your MongoDB>
      MONGO_PASS: <Password of your MongoDB user>
      MONGO_DB: <The database from which you want to pull the data>
      MONGO_HOST: <The host running MongoDB>
